// styles.js

const styles = {
  "border-radius": [
    { value: "rounded-none", desc: "border-radius: 0px;" },
    { value: "rounded-sm", desc: "border-radius: 0.125rem; /* 2px */" },
    { value: "rounded", desc: "border-radius: 0.25rem; /* 4px */" },
    { value: "rounded-md", desc: "border-radius: 0.375rem; /* 6px */" },
    { value: "rounded-lg", desc: "border-radius: 0.5rem; /* 8px */" },
    { value: "rounded-xl", desc: "border-radius: 0.75rem; /* 12px */" },
    { value: "rounded-2xl", desc: "border-radius: 1rem; /* 16px */" },
    { value: "rounded-3xl", desc: "border-radius: 1.5rem; /* 24px */" },
    { value: "rounded-full", desc: "border-radius: 9999px;" },
  ],
  position: [
    { value: "static", desc: "position: static;" },
    { value: "fixed", desc: "position: fixed;" },
    { value: "absolute", desc: "position: absolute;" },
    { value: "relative", desc: "position: relative;" },
    { value: "sticky", desc: "position: sticky;" },
  ],
  visibility: [
    { value: "visible", desc: "visibility: visible;" },
    { value: "invisible", desc: "visibility: hidden;" },
    { value: "collapse", desc: "visibility: collapse;" },
  ],
  "z-index": [
    { value: "z-0", desc: "z-index: 0;" },
    { value: "z-10", desc: "z-index: 10;" },
    { value: "z-20", desc: "z-index: 20;" },
    { value: "z-30", desc: "z-index: 30;" },
    { value: "z-40", desc: "z-index: 40;" },
    { value: "z-50", desc: "z-index: 50;" },
    { value: "z-auto", desc: "z-index: auto;" },
  ],
  overflow: [
    { value: "overflow-auto", desc: "overflow: auto;" },
    { value: "overflow-hidden", desc: "overflow: hidden;" },
    { value: "overflow-clip", desc: "overflow: clip;" },
    { value: "overflow-visible", desc: "overflow: visible;" },
    { value: "overflow-scroll", desc: "overflow: scroll;" },
  ],
  "object-fit": [
    { value: "object-contain", desc: "object-fit: contain;" },
    { value: "object-cover", desc: "object-fit: cover;" },
    { value: "object-fill", desc: "object-fit: fill;" },
    { value: "object-none", desc: "object-fit: none;" },
    { value: "object-scale-down", desc: "object-fit: scale-down;" },
  ],
  display: [
    { value: "block", desc: "display: block;" },
    { value: "inline-block", desc: "display: inline-block;" },
    { value: "inline", desc: "display: inline;" },
    { value: "flex", desc: "display: flex;" },
    { value: "inline-flex", desc: "display: inline-flex;" },
    { value: "table", desc: "display: table;" },
    { value: "inline-table", desc: "display: inline-table;" },
    { value: "table-caption", desc: "display: table-caption;" },
    { value: "table-cell", desc: "display: table-cell;" },
    { value: "table-column", desc: "display: table-column;" },
    { value: "table-column-group", desc: "display: table-column-group;" },
    { value: "table-footer-group", desc: "display: table-footer-group;" },
    { value: "table-header-group", desc: "display: table-header-group;" },
    { value: "table-row-group", desc: "display: table-row-group;" },
    { value: "table-row", desc: "display: table-row;" },
    { value: "flow-root", desc: "display: flow-root;" },
    { value: "grid", desc: "display: grid;" },
    { value: "inline-grid", desc: "display: inline-grid;" },
    { value: "contents", desc: "display: contents;" },
    { value: "list-item", desc: "display: list-item;" },
    { value: "hidden", desc: "display: none;" },
  ],
  "box-sizing": [
    { value: "box-border", desc: "box-sizing: border-box;" },
    { value: "box-content", desc: "box-sizing: content-box;" },
  ],
  "justify-items": [
    { value: "justify-items-start", desc: "justify-items: start;" },
    { value: "justify-items-end", desc: "justify-items: end;" },
    { value: "justify-items-center", desc: "justify-items: center;" },
    { value: "justify-items-stretch", desc: "justify-items: stretch;" },
  ],
  "justify-content": [
    { value: "justify-normal", desc: "justify-content: normal;" },
    { value: "justify-start", desc: "justify-content: flex-start;" },
    { value: "justify-end", desc: "justify-content: flex-end;" },
    { value: "justify-center", desc: "justify-content: center;" },
    { value: "justify-between", desc: "justify-content: space-between;" },
    { value: "justify-around", desc: "justify-content: space-around;" },
    { value: "justify-evenly", desc: "justify-content: space-evenly;" },
    { value: "justify-stretch", desc: "justify-content: stretch;" },
  ],
  "align-items": [
    { value: "items-start", desc: "align-items: flex-start;" },
    { value: "items-end", desc: "align-items: flex-end;" },
    { value: "items-center", desc: "align-items: center;" },
    { value: "items-baseline", desc: "align-items: baseline;" },
    { value: "items-stretch", desc: "align-items: stretch;" },
  ],
  "text-decoration": [
    { value: "underline", desc: "text-decoration-line: underline;" },
    { value: "overline", desc: "text-decoration-line: overline;" },
    { value: "line-through", desc: "text-decoration-line: line-through;" },
    { value: "no-underline", desc: "text-decoration-line: none;" },
  ],
  "font-size": [
    {
      value: "text-xs",
      desc: "font-size: 0.75rem; /* 12px */ line-height: 1rem; /* 16px */",
    },
    {
      value: "text-sm",
      desc: "font-size: 0.875rem; /* 14px */ line-height: 1.25rem; /* 20px */",
    },
    {
      value: "text-base",
      desc: "font-size: 1rem; /* 16px */ line-height: 1.5rem; /* 24px */",
    },
    {
      value: "text-lg",
      desc: "font-size: 1.125rem; /* 18px */ line-height: 1.75rem; /* 28px */",
    },
    {
      value: "text-xl",
      desc: "font-size: 1.25rem; /* 20px */ line-height: 1.75rem; /* 28px */",
    },
    {
      value: "text-2xl",
      desc: "font-size: 1.5rem; /* 24px */ line-height: 2rem; /* 32px */",
    },
    {
      value: "text-3xl",
      desc: "font-size: 1.875rem; /* 30px */ line-height: 2.25rem; /* 36px */",
    },
    {
      value: "text-4xl",
      desc: "font-size: 2.25rem; /* 36px */ line-height: 2.5rem; /* 40px */",
    },
    { value: "text-5xl", desc: "font-size: 3rem; /* 48px */ line-height: 1;" },
    {
      value: "text-6xl",
      desc: "font-size: 3.75rem; /* 60px */ line-height: 1;",
    },
    {
      value: "text-7xl",
      desc: "font-size: 4.5rem; /* 72px */ line-height: 1;",
    },
    { value: "text-8xl", desc: "font-size: 6rem; /* 96px */ line-height: 1;" },
    { value: "text-9xl", desc: "font-size: 8rem; /* 128px */ line-height: 1;" },
  ],
  "font-weight": [
    { value: "font-thin", desc: "font-weight: 100;" },
    { value: "font-extralight", desc: "font-weight: 200;" },
    { value: "font-light", desc: "font-weight: 300;" },
    { value: "font-normal", desc: "font-weight: 400;" },
    { value: "font-medium", desc: "font-weight: 500;" },
    { value: "font-semibold", desc: "font-weight: 600;" },
    { value: "font-bold", desc: "font-weight: 700;" },
    { value: "font-extrabold", desc: "font-weight: 800;" },
    { value: "font-black", desc: "font-weight: 900;" },
  ],
  "text-align": [
    { value: "text-left", desc: "text-align: left;" },
    { value: "text-center", desc: "text-align: center;" },
    { value: "text-right", desc: "text-align: right;" },
    { value: "text-justify", desc: "text-align: justify;" },
    { value: "text-start", desc: "text-align: start;" },
    { value: "text-end", desc: "text-align: end;" },
  ],
  "line-height": [
    { value: "leading-3", desc: "line-height: .75rem; /* 12px */" },
    { value: "leading-4", desc: "line-height: 1rem; /* 16px */" },
    { value: "leading-5", desc: "line-height: 1.25rem; /* 20px */" },
    { value: "leading-6", desc: "line-height: 1.5rem; /* 24px */" },
    { value: "leading-7", desc: "line-height: 1.75rem; /* 28px */" },
    { value: "leading-8", desc: "line-height: 2rem; /* 32px */" },
    { value: "leading-9", desc: "line-height: 2.25rem; /* 36px */" },
    { value: "leading-10", desc: "line-height: 2.5rem; /* 40px */" },
    { value: "leading-none", desc: "line-height: 1;" },
    { value: "leading-tight", desc: "line-height: 1.25;" },
    { value: "leading-snug", desc: "line-height: 1.375;" },
    { value: "leading-normal", desc: "line-height: 1.5;" },
    { value: "leading-relaxed", desc: "line-height: 1.625;" },
    { value: "leading-loose", desc: "line-height: 2;" },
  ],
  "text-overflow": [
    {
      value: "truncate",
      desc: "overflow: hidden; text-overflow: ellipsis; white-space: nowrap;",
    },
    { value: "text-ellipsis", desc: "text-overflow: ellipsis;" },
    { value: "text-clip", desc: "text-overflow: clip;" },
  ],
  "text-wrap": [
    { value: "text-wrap", desc: "text-wrap: wrap;" },
    { value: "text-nowrap", desc: "text-wrap: nowrap;" },
    { value: "text-balance", desc: "text-wrap: balance;" },
    { value: "text-pretty", desc: "text-wrap: pretty;" },
  ],
  "text-transform": [
    { value: "uppercase", desc: "text-transform: uppercase;" },
    { value: "lowercase", desc: "text-transform: lowercase;" },
    { value: "capitalize", desc: "text-transform: capitalize;" },
    { value: "normal-case", desc: "text-transform: none;" },
  ],
  "word-break": [
    {
      value: "break-normal",
      desc: "overflow-wrap: normal; word-break: normal;",
    },
    { value: "break-words", desc: "overflow-wrap: break-word;" },
    { value: "break-all", desc: "word-break: break-all;" },
    { value: "break-keep", desc: "word-break: keep-all;" },
  ],
  "border-width": [
    { value: "border-0", desc: "border-width: 0px;" },
    { value: "border-2", desc: "border-width: 2px;" },
    { value: "border-4", desc: "border-width: 4px;" },
    { value: "border-8", desc: "border-width: 8px;" },
    { value: "border", desc: "border-width: 1px;" },
    {
      value: "border-x-0",
      desc: "border-left-width: 0px; border-right-width: 0px;",
    },
    {
      value: "border-x-2",
      desc: "border-left-width: 2px; border-right-width: 2px;",
    },
    {
      value: "border-x-4",
      desc: "border-left-width: 4px; border-right-width: 4px;",
    },
    {
      value: "border-x-8",
      desc: "border-left-width: 8px; border-right-width: 8px;",
    },
    {
      value: "border-x",
      desc: "border-left-width: 1px; border-right-width: 1px;",
    },
    {
      value: "border-y-0",
      desc: "border-top-width: 0px; border-bottom-width: 0px;",
    },
    {
      value: "border-y-2",
      desc: "border-top-width: 2px; border-bottom-width: 2px;",
    },
    {
      value: "border-y-4",
      desc: "border-top-width: 4px; border-bottom-width: 4px;",
    },
    {
      value: "border-y-8",
      desc: "border-top-width: 8px; border-bottom-width: 8px;",
    },
    {
      value: "border-y",
      desc: "border-top-width: 1px; border-bottom-width: 1px;",
    },
    { value: "border-s-0", desc: "border-inline-start-width: 0px;" },
    { value: "border-s-2", desc: "border-inline-start-width: 2px;" },
    { value: "border-s-4", desc: "border-inline-start-width: 4px;" },
    { value: "border-s-8", desc: "border-inline-start-width: 8px;" },
    { value: "border-s", desc: "border-inline-start-width: 1px;" },
    { value: "border-e-0", desc: "border-inline-end-width: 0px;" },
    { value: "border-e-2", desc: "border-inline-end-width: 2px;" },
    { value: "border-e-4", desc: "border-inline-end-width: 4px;" },
    { value: "border-e-8", desc: "border-inline-end-width: 8px;" },
    { value: "border-e", desc: "border-inline-end-width: 1px;" },
    { value: "border-t-0", desc: "border-top-width: 0px;" },
    { value: "border-t-2", desc: "border-top-width: 2px;" },
    { value: "border-t-4", desc: "border-top-width: 4px;" },
    { value: "border-t-8", desc: "border-top-width: 8px;" },
    { value: "border-t", desc: "border-top-width: 1px;" },
    { value: "border-r-0", desc: "border-right-width: 0px;" },
    { value: "border-r-2", desc: "border-right-width: 2px;" },
    { value: "border-r-4", desc: "border-right-width: 4px;" },
    { value: "border-r-8", desc: "border-right-width: 8px;" },
    { value: "border-r", desc: "border-right-width: 1px;" },
    { value: "border-b-0", desc: "border-bottom-width: 0px;" },
    { value: "border-b-2", desc: "border-bottom-width: 2px;" },
    { value: "border-b-4", desc: "border-bottom-width: 4px;" },
    { value: "border-b-8", desc: "border-bottom-width: 8px;" },
    { value: "border-b", desc: "border-bottom-width: 1px;" },
    { value: "border-l-0", desc: "border-left-width: 0px;" },
    { value: "border-l-2", desc: "border-left-width: 2px;" },
    { value: "border-l-4", desc: "border-left-width: 4px;" },
    { value: "border-l-8", desc: "border-left-width: 8px;" },
    { value: "border-l", desc: "border-left-width: 1px;" },
  ],
  "border-style": [
    { value: "border-solid", desc: "border-style: solid;" },
    { value: "border-dashed", desc: "border-style: dashed;" },
    { value: "border-dotted", desc: "border-style: dotted;" },
    { value: "border-double", desc: "border-style: double;" },
    { value: "border-hidden", desc: "border-style: hidden;" },
    { value: "border-none", desc: "border-style: none;" },
  ],
  "box-shadow": [
    {
      value: "shadow-sm",
      desc: "box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.05);",
    },
    {
      value: "shadow",
      desc: "box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1);",
    },
    {
      value: "shadow-md",
      desc: "box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1);",
    },
    {
      value: "shadow-lg",
      desc: "box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.1);",
    },
    {
      value: "shadow-xl",
      desc: "box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1);",
    },
    {
      value: "shadow-2xl",
      desc: "box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);",
    },
    {
      value: "shadow-inner",
      desc: "box-shadow: inset 0 2px 4px 0 rgba(0, 0, 0, 0.05);",
    },
    { value: "shadow-none", desc: "box-shadow: none;" },
  ],
  opacity: [
    { value: "opacity-0", desc: "opacity: 0;" },
    { value: "opacity-5", desc: "opacity: 0.05;" },
    { value: "opacity-10", desc: "opacity: 0.1;" },
    { value: "opacity-15", desc: "opacity: 0.15;" },
    { value: "opacity-20", desc: "opacity: 0.2;" },
    { value: "opacity-25", desc: "opacity: 0.25;" },
    { value: "opacity-30", desc: "opacity: 0.3;" },
    { value: "opacity-35", desc: "opacity: 0.35;" },
    { value: "opacity-40", desc: "opacity: 0.4;" },
    { value: "opacity-45", desc: "opacity: 0.45;" },
    { value: "opacity-50", desc: "opacity: 0.5;" },
    { value: "opacity-55", desc: "opacity: 0.55;" },
    { value: "opacity-60", desc: "opacity: 0.6;" },
    { value: "opacity-65", desc: "opacity: 0.65;" },
    { value: "opacity-70", desc: "opacity: 0.7;" },
    { value: "opacity-75", desc: "opacity: 0.75;" },
    { value: "opacity-80", desc: "opacity: 0.8;" },
    { value: "opacity-85", desc: "opacity: 0.85;" },
    { value: "opacity-90", desc: "opacity: 0.9;" },
    { value: "opacity-95", desc: "opacity: 0.95;" },
    { value: "opacity-100", desc: "opacity: 1;" },
  ],
  rotate: [
    { value: "rotate-0", desc: "transform: rotate(0deg);" },
    { value: "rotate-1", desc: "transform: rotate(1deg);" },
    { value: "rotate-2", desc: "transform: rotate(2deg);" },
    { value: "rotate-3", desc: "transform: rotate(3deg);" },
    { value: "rotate-6", desc: "transform: rotate(6deg);" },
    { value: "rotate-12", desc: "transform: rotate(12deg);" },
    { value: "rotate-45", desc: "transform: rotate(45deg);" },
    { value: "rotate-90", desc: "transform: rotate(90deg);" },
    { value: "rotate-180", desc: "transform: rotate(180deg);" },
  ],
  cursor: [
    { value: "cursor-auto", desc: "cursor: auto;" },
    { value: "cursor-default", desc: "cursor: default;" },
    { value: "cursor-pointer", desc: "cursor: pointer;" },
    { value: "cursor-wait", desc: "cursor: wait;" },
    { value: "cursor-text", desc: "cursor: text;" },
    { value: "cursor-move", desc: "cursor: move;" },
    { value: "cursor-help", desc: "cursor: help;" },
    { value: "cursor-not-allowed", desc: "cursor: not-allowed;" },
    { value: "cursor-none", desc: "cursor: none;" },
    { value: "cursor-context-menu", desc: "cursor: context-menu;" },
    { value: "cursor-progress", desc: "cursor: progress;" },
    { value: "cursor-cell", desc: "cursor: cell;" },
    { value: "cursor-crosshair", desc: "cursor: crosshair;" },
    { value: "cursor-vertical-text", desc: "cursor: vertical-text;" },
    { value: "cursor-alias", desc: "cursor: alias;" },
    { value: "cursor-copy", desc: "cursor: copy;" },
    { value: "cursor-no-drop", desc: "cursor: no-drop;" },
    { value: "cursor-grab", desc: "cursor: grab;" },
    { value: "cursor-grabbing", desc: "cursor: grabbing;" },
    { value: "cursor-all-scroll", desc: "cursor: all-scroll;" },
    { value: "cursor-col-resize", desc: "cursor: col-resize;" },
    { value: "cursor-row-resize", desc: "cursor: row-resize;" },
    { value: "cursor-n-resize", desc: "cursor: n-resize;" },
    { value: "cursor-e-resize", desc: "cursor: e-resize;" },
    { value: "cursor-s-resize", desc: "cursor: s-resize;" },
    { value: "cursor-w-resize", desc: "cursor: w-resize;" },
    { value: "cursor-ne-resize", desc: "cursor: ne-resize;" },
    { value: "cursor-nw-resize", desc: "cursor: nw-resize;" },
    { value: "cursor-se-resize", desc: "cursor: se-resize;" },
    { value: "cursor-sw-resize", desc: "cursor: sw-resize;" },
    { value: "cursor-ew-resize", desc: "cursor: ew-resize;" },
    { value: "cursor-ns-resize", desc: "cursor: ns-resize;" },
    { value: "cursor-nesw-resize", desc: "cursor: nesw-resize;" },
    { value: "cursor-nwse-resize", desc: "cursor: nwse-resize;" },
    { value: "cursor-zoom-in", desc: "cursor: zoom-in;" },
    { value: "cursor-zoom-out", desc: "cursor: zoom-out;" },
  ],
  padding: [
    { value: "p-0", desc: "padding: 0px;" },
    { value: "p-px", desc: "padding: 1px;" },
    { value: "p-0.5", desc: "padding: 0.125rem; /* 2px */" },
    { value: "p-1", desc: "padding: 0.25rem; /* 4px */" },
    { value: "p-1.5", desc: "padding: 0.375rem; /* 6px */" },
    { value: "p-2", desc: "padding: 0.5rem; /* 8px */" },
    { value: "p-2.5", desc: "padding: 0.625rem; /* 10px */" },
    { value: "p-3", desc: "padding: 0.75rem; /* 12px */" },
    { value: "p-3.5", desc: "padding: 0.875rem; /* 14px */" },
    { value: "p-4", desc: "padding: 1rem; /* 16px */" },
    { value: "p-5", desc: "padding: 1.25rem; /* 20px */" },
    { value: "p-6", desc: "padding: 1.5rem; /* 24px */" },
    { value: "p-7", desc: "padding: 1.75rem; /* 28px */" },
    { value: "p-8", desc: "padding: 2rem; /* 32px */" },
    { value: "p-9", desc: "padding: 2.25rem; /* 36px */" },
    { value: "p-10", desc: "padding: 2.5rem; /* 40px */" },
    { value: "p-11", desc: "padding: 2.75rem; /* 44px */" },
    { value: "p-12", desc: "padding: 3rem; /* 48px */" },
    { value: "p-14", desc: "padding: 3.5rem; /* 56px */" },
    { value: "p-16", desc: "padding: 4rem; /* 64px */" },
    { value: "p-20", desc: "padding: 5rem; /* 80px */" },
    { value: "p-24", desc: "padding: 6rem; /* 96px */" },
    { value: "p-28", desc: "padding: 7rem; /* 112px */" },
    { value: "p-32", desc: "padding: 8rem; /* 128px */" },
    { value: "p-36", desc: "padding: 9rem; /* 144px */" },
    { value: "p-40", desc: "padding: 10rem; /* 160px */" },
    { value: "p-44", desc: "padding: 11rem; /* 176px */" },
    { value: "p-48", desc: "padding: 12rem; /* 192px */" },
    { value: "p-52", desc: "padding: 13rem; /* 208px */" },
    { value: "p-56", desc: "padding: 14rem; /* 224px */" },
    { value: "p-60", desc: "padding: 15rem; /* 240px */" },
    { value: "p-64", desc: "padding: 16rem; /* 256px */" },
    { value: "p-72", desc: "padding: 18rem; /* 288px */" },
    { value: "p-80", desc: "padding: 20rem; /* 320px */" },
    { value: "p-96", desc: "padding: 24rem; /* 384px */" },
  ],
  margin: [
    { value: "m-0", desc: "margin: 0px;" },
    { value: "m-px", desc: "margin: 1px;" },
    { value: "m-0.5", desc: "margin: 0.125rem; /* 2px */" },
    { value: "m-1", desc: "margin: 0.25rem; /* 4px */" },
    { value: "m-1.5", desc: "margin: 0.375rem; /* 6px */" },
    { value: "m-2", desc: "margin: 0.5rem; /* 8px */" },
    { value: "m-2.5", desc: "margin: 0.625rem; /* 10px */" },
    { value: "m-3", desc: "margin: 0.75rem; /* 12px */" },
    { value: "m-3.5", desc: "margin: 0.875rem; /* 14px */" },
    { value: "m-4", desc: "margin: 1rem; /* 16px */" },
    { value: "m-5", desc: "margin: 1.25rem; /* 20px */" },
    { value: "m-6", desc: "margin: 1.5rem; /* 24px */" },
    { value: "m-7", desc: "margin: 1.75rem; /* 28px */" },
    { value: "m-8", desc: "margin: 2rem; /* 32px */" },
    { value: "m-9", desc: "margin: 2.25rem; /* 36px */" },
    { value: "m-10", desc: "margin: 2.5rem; /* 40px */" },
    { value: "m-11", desc: "margin: 2.75rem; /* 44px */" },
    { value: "m-12", desc: "margin: 3rem; /* 48px */" },
    { value: "m-14", desc: "margin: 3.5rem; /* 56px */" },
    { value: "m-16", desc: "margin: 4rem; /* 64px */" },
    { value: "m-20", desc: "margin: 5rem; /* 80px */" },
    { value: "m-24", desc: "margin: 6rem; /* 96px */" },
    { value: "m-28", desc: "margin: 7rem; /* 112px */" },
    { value: "m-32", desc: "margin: 8rem; /* 128px */" },
    { value: "m-36", desc: "margin: 9rem; /* 144px */" },
    { value: "m-40", desc: "margin: 10rem; /* 160px */" },
    { value: "m-44", desc: "margin: 11rem; /* 176px */" },
    { value: "m-48", desc: "margin: 12rem; /* 192px */" },
    { value: "m-52", desc: "margin: 13rem; /* 208px */" },
    { value: "m-56", desc: "margin: 14rem; /* 224px */" },
    { value: "m-60", desc: "margin: 15rem; /* 240px */" },
    { value: "m-64", desc: "margin: 16rem; /* 256px */" },
    { value: "m-72", desc: "margin: 18rem; /* 288px */" },
    { value: "m-80", desc: "margin: 20rem; /* 320px */" },
    { value: "m-96", desc: "margin: 24rem; /* 384px */" },
    { value: "m-auto", desc: "margin: auto;" },
  ],
  width: [
    { value: "w-0", desc: "width: 0px;" },
    { value: "w-px", desc: "width: 1px;" },
    { value: "w-0.5", desc: "width: 0.125rem; /* 2px */" },
    { value: "w-1", desc: "width: 0.25rem; /* 4px */" },
    { value: "w-1.5", desc: "width: 0.375rem; /* 6px */" },
    { value: "w-2", desc: "width: 0.5rem; /* 8px */" },
    { value: "w-2.5", desc: "width: 0.625rem; /* 10px */" },
    { value: "w-3", desc: "width: 0.75rem; /* 12px */" },
    { value: "w-3.5", desc: "width: 0.875rem; /* 14px */" },
    { value: "w-4", desc: "width: 1rem; /* 16px */" },
    { value: "w-5", desc: "width: 1.25rem; /* 20px */" },
    { value: "w-6", desc: "width: 1.5rem; /* 24px */" },
    { value: "w-7", desc: "width: 1.75rem; /* 28px */" },
    { value: "w-8", desc: "width: 2rem; /* 32px */" },
    { value: "w-9", desc: "width: 2.25rem; /* 36px */" },
    { value: "w-10", desc: "width: 2.5rem; /* 40px */" },
    { value: "w-11", desc: "width: 2.75rem; /* 44px */" },
    { value: "w-12", desc: "width: 3rem; /* 48px */" },
    { value: "w-14", desc: "width: 3.5rem; /* 56px */" },
    { value: "w-16", desc: "width: 4rem; /* 64px */" },
    { value: "w-20", desc: "width: 5rem; /* 80px */" },
    { value: "w-24", desc: "width: 6rem; /* 96px */" },
    { value: "w-28", desc: "width: 7rem; /* 112px */" },
    { value: "w-32", desc: "width: 8rem; /* 128px */" },
    { value: "w-36", desc: "width: 9rem; /* 144px */" },
    { value: "w-40", desc: "width: 10rem; /* 160px */" },
    { value: "w-44", desc: "width: 11rem; /* 176px */" },
    { value: "w-48", desc: "width: 12rem; /* 192px */" },
    { value: "w-52", desc: "width: 13rem; /* 208px */" },
    { value: "w-56", desc: "width: 14rem; /* 224px */" },
    { value: "w-60", desc: "width: 15rem; /* 240px */" },
    { value: "w-64", desc: "width: 16rem; /* 256px */" },
    { value: "w-72", desc: "width: 18rem; /* 288px */" },
    { value: "w-80", desc: "width: 20rem; /* 320px */" },
    { value: "w-96", desc: "width: 24rem; /* 384px */" },
    { value: "w-auto", desc: "width: auto;" },
    { value: "w-1/2", desc: "width: 50%;" },
    { value: "w-1/3", desc: "width: 33.333333%;" },
    { value: "w-2/3", desc: "width: 66.666667%;" },
    { value: "w-1/4", desc: "width: 25%;" },
    { value: "w-2/4", desc: "width: 50%;" },
    { value: "w-3/4", desc: "width: 75%;" },
    { value: "w-1/5", desc: "width: 20%;" },
    { value: "w-2/5", desc: "width: 40%;" },
    { value: "w-3/5", desc: "width: 60%;" },
    { value: "w-4/5", desc: "width: 80%;" },
    { value: "w-1/6", desc: "width: 16.666667%;" },
    { value: "w-2/6", desc: "width: 33.333333%;" },
    { value: "w-3/6", desc: "width: 50%;" },
    { value: "w-4/6", desc: "width: 66.666667%;" },
    { value: "w-5/6", desc: "width: 83.333333%;" },
    { value: "w-1/12", desc: "width: 8.333333%;" },
    { value: "w-2/12", desc: "width: 16.666667%;" },
    { value: "w-3/12", desc: "width: 25%;" },
    { value: "w-4/12", desc: "width: 33.333333%;" },
    { value: "w-5/12", desc: "width: 41.666667%;" },
    { value: "w-6/12", desc: "width: 50%;" },
    { value: "w-7/12", desc: "width: 58.333333%;" },
    { value: "w-8/12", desc: "width: 66.666667%;" },
    { value: "w-9/12", desc: "width: 75%;" },
    { value: "w-10/12", desc: "width: 83.333333%;" },
    { value: "w-11/12", desc: "width: 91.666667%;" },
    { value: "w-full", desc: "width: 100%;" },
    { value: "w-screen", desc: "width: 100vw;" },
    { value: "w-min", desc: "width: min-content;" },
    { value: "w-max", desc: "width: max-content;" },
    { value: "w-fit", desc: "width: fit-content;" },
  ],
  "min-width": [
    { value: "min-w-0", desc: "min-width: 0px;" },
    { value: "min-w-1", desc: "min-width: 0.25rem; /* 4px */" },
    { value: "min-w-2", desc: "min-width: 0.5rem; /* 8px */" },
    { value: "min-w-3", desc: "min-width: 0.75rem; /* 12px */" },
    { value: "min-w-4", desc: "min-width: 1rem; /* 16px */" },
    { value: "min-w-5", desc: "min-width: 1.25rem; /* 20px */" },
    { value: "min-w-6", desc: "min-width: 1.5rem; /* 24px */" },
    { value: "min-w-7", desc: "min-width: 1.75rem; /* 28px */" },
    { value: "min-w-8", desc: "min-width: 2rem; /* 32px */" },
    { value: "min-w-9", desc: "min-width: 2.25rem; /* 36px */" },
    { value: "min-w-10", desc: "min-width: 2.5rem; /* 40px */" },
    { value: "min-w-11", desc: "min-width: 2.75rem; /* 44px */" },
    { value: "min-w-12", desc: "min-width: 3rem; /* 48px */" },
    { value: "min-w-14", desc: "min-width: 3.5rem; /* 56px */" },
    { value: "min-w-16", desc: "min-width: 4rem; /* 64px */" },
    { value: "min-w-20", desc: "min-width: 5rem; /* 80px */" },
    { value: "min-w-24", desc: "min-width: 6rem; /* 96px */" },
    { value: "min-w-28", desc: "min-width: 7rem; /* 112px */" },
    { value: "min-w-32", desc: "min-width: 8rem; /* 128px */" },
    { value: "min-w-36", desc: "min-width: 9rem; /* 144px */" },
    { value: "min-w-40", desc: "min-width: 10rem; /* 160px */" },
    { value: "min-w-44", desc: "min-width: 11rem; /* 176px */" },
    { value: "min-w-48", desc: "min-width: 12rem; /* 192px */" },
    { value: "min-w-52", desc: "min-width: 13rem; /* 208px */" },
    { value: "min-w-56", desc: "min-width: 14rem; /* 224px */" },
    { value: "min-w-60", desc: "min-width: 15rem; /* 240px */" },
    { value: "min-w-64", desc: "min-width: 16rem; /* 256px */" },
    { value: "min-w-72", desc: "min-width: 18rem; /* 288px */" },
    { value: "min-w-80", desc: "min-width: 20rem; /* 320px */" },
    { value: "min-w-96", desc: "min-width: 24rem; /* 384px */" },
    { value: "min-w-px", desc: "min-width: 1px;" },
    { value: "min-w-0.5", desc: "min-width: 0.125rem; /* 2px */" },
    { value: "min-w-1.5", desc: "min-width: 0.375rem; /* 6px */" },
    { value: "min-w-2.5", desc: "min-width: 0.625rem; /* 10px */" },
    { value: "min-w-3.5", desc: "min-width: 0.875rem; /* 14px */" },
    { value: "min-w-full", desc: "min-width: 100%;" },
    { value: "min-w-min", desc: "min-width: min-content;" },
    { value: "min-w-max", desc: "min-width: max-content;" },
    { value: "min-w-fit", desc: "min-width: fit-content;" },
  ],
  "max-width": [
    { value: "max-w-0", desc: "max-width: 0px;" },
    { value: "max-w-px", desc: "max-width: 1px;" },
    { value: "max-w-0.5", desc: "max-width: 0.125rem; /* 2px */" },
    { value: "max-w-1", desc: "max-width: 0.25rem; /* 4px */" },
    { value: "max-w-1.5", desc: "max-width: 0.375rem; /* 6px */" },
    { value: "max-w-2", desc: "max-width: 0.5rem; /* 8px */" },
    { value: "max-w-2.5", desc: "max-width: 0.625rem; /* 10px */" },
    { value: "max-w-3", desc: "max-width: 0.75rem; /* 12px */" },
    { value: "max-w-3.5", desc: "max-width: 0.875rem; /* 14px */" },
    { value: "max-w-4", desc: "max-width: 1rem; /* 16px */" },
    { value: "max-w-5", desc: "max-width: 1.25rem; /* 20px */" },
    { value: "max-w-6", desc: "max-width: 1.5rem; /* 24px */" },
    { value: "max-w-7", desc: "max-width: 1.75rem; /* 28px */" },
    { value: "max-w-8", desc: "max-width: 2rem; /* 32px */" },
    { value: "max-w-9", desc: "max-width: 2.25rem; /* 36px */" },
    { value: "max-w-10", desc: "max-width: 2.5rem; /* 40px */" },
    { value: "max-w-11", desc: "max-width: 2.75rem; /* 44px */" },
    { value: "max-w-12", desc: "max-width: 3rem; /* 48px */" },
    { value: "max-w-14", desc: "max-width: 3.5rem; /* 56px */" },
    { value: "max-w-16", desc: "max-width: 4rem; /* 64px */" },
    { value: "max-w-20", desc: "max-width: 5rem; /* 80px */" },
    { value: "max-w-24", desc: "max-width: 6rem; /* 96px */" },
    { value: "max-w-28", desc: "max-width: 7rem; /* 112px */" },
    { value: "max-w-32", desc: "max-width: 8rem; /* 128px */" },
    { value: "max-w-36", desc: "max-width: 9rem; /* 144px */" },
    { value: "max-w-40", desc: "max-width: 10rem; /* 160px */" },
    { value: "max-w-44", desc: "max-width: 11rem; /* 176px */" },
    { value: "max-w-48", desc: "max-width: 12rem; /* 192px */" },
    { value: "max-w-52", desc: "max-width: 13rem; /* 208px */" },
    { value: "max-w-56", desc: "max-width: 14rem; /* 224px */" },
    { value: "max-w-60", desc: "max-width: 15rem; /* 240px */" },
    { value: "max-w-64", desc: "max-width: 16rem; /* 256px */" },
    { value: "max-w-72", desc: "max-width: 18rem; /* 288px */" },
    { value: "max-w-80", desc: "max-width: 20rem; /* 320px */" },
    { value: "max-w-96", desc: "max-width: 24rem; /* 384px */" },
    { value: "max-w-none", desc: "max-width: none;" },
    { value: "max-w-xs", desc: "max-width: 20rem; /* 320px */" },
    { value: "max-w-sm", desc: "max-width: 24rem; /* 384px */" },
    { value: "max-w-md", desc: "max-width: 28rem; /* 448px */" },
    { value: "max-w-lg", desc: "max-width: 32rem; /* 512px */" },
    { value: "max-w-xl", desc: "max-width: 36rem; /* 576px */" },
    { value: "max-w-2xl", desc: "max-width: 42rem; /* 672px */" },
    { value: "max-w-3xl", desc: "max-width: 48rem; /* 768px */" },
    { value: "max-w-4xl", desc: "max-width: 56rem; /* 896px */" },
    { value: "max-w-5xl", desc: "max-width: 64rem; /* 1024px */" },
    { value: "max-w-6xl", desc: "max-width: 72rem; /* 1152px */" },
    { value: "max-w-7xl", desc: "max-width: 80rem; /* 1280px */" },
    { value: "max-w-full", desc: "max-width: 100%;" },
    { value: "max-w-min", desc: "max-width: min-content;" },
    { value: "max-w-max", desc: "max-width: max-content;" },
    { value: "max-w-fit", desc: "max-width: fit-content;" },
    { value: "max-w-prose", desc: "max-width: 65ch;" },
    { value: "max-w-screen-sm", desc: "max-width: 640px;" },
    { value: "max-w-screen-md", desc: "max-width: 768px;" },
    { value: "max-w-screen-lg", desc: "max-width: 1024px;" },
    { value: "max-w-screen-xl", desc: "max-width: 1280px;" },
    { value: "max-w-screen-2xl", desc: "max-width: 1536px;" },
  ],
  height: [
    { value: "h-0", desc: "height: 0px;" },
    { value: "h-px", desc: "height: 1px;" },
    { value: "h-0.5", desc: "height: 0.125rem; /* 2px */" },
    { value: "h-1", desc: "height: 0.25rem; /* 4px */" },
    { value: "h-1.5", desc: "height: 0.375rem; /* 6px */" },
    { value: "h-2", desc: "height: 0.5rem; /* 8px */" },
    { value: "h-2.5", desc: "height: 0.625rem; /* 10px */" },
    { value: "h-3", desc: "height: 0.75rem; /* 12px */" },
    { value: "h-3.5", desc: "height: 0.875rem; /* 14px */" },
    { value: "h-4", desc: "height: 1rem; /* 16px */" },
    { value: "h-5", desc: "height: 1.25rem; /* 20px */" },
    { value: "h-6", desc: "height: 1.5rem; /* 24px */" },
    { value: "h-7", desc: "height: 1.75rem; /* 28px */" },
    { value: "h-8", desc: "height: 2rem; /* 32px */" },
    { value: "h-9", desc: "height: 2.25rem; /* 36px */" },
    { value: "h-10", desc: "height: 2.5rem; /* 40px */" },
    { value: "h-11", desc: "height: 2.75rem; /* 44px */" },
    { value: "h-12", desc: "height: 3rem; /* 48px */" },
    { value: "h-14", desc: "height: 3.5rem; /* 56px */" },
    { value: "h-16", desc: "height: 4rem; /* 64px */" },
    { value: "h-20", desc: "height: 5rem; /* 80px */" },
    { value: "h-24", desc: "height: 6rem; /* 96px */" },
    { value: "h-28", desc: "height: 7rem; /* 112px */" },
    { value: "h-32", desc: "height: 8rem; /* 128px */" },
    { value: "h-36", desc: "height: 9rem; /* 144px */" },
    { value: "h-40", desc: "height: 10rem; /* 160px */" },
    { value: "h-44", desc: "height: 11rem; /* 176px */" },
    { value: "h-48", desc: "height: 12rem; /* 192px */" },
    { value: "h-52", desc: "height: 13rem; /* 208px */" },
    { value: "h-56", desc: "height: 14rem; /* 224px */" },
    { value: "h-60", desc: "height: 15rem; /* 240px */" },
    { value: "h-64", desc: "height: 16rem; /* 256px */" },
    { value: "h-72", desc: "height: 18rem; /* 288px */" },
    { value: "h-80", desc: "height: 20rem; /* 320px */" },
    { value: "h-96", desc: "height: 24rem; /* 384px */" },
    { value: "h-auto", desc: "height: auto;" },
    { value: "h-1/2", desc: "height: 50%;" },
    { value: "h-1/3", desc: "height: 33.333333%;" },
    { value: "h-2/3", desc: "height: 66.666667%;" },
    { value: "h-1/4", desc: "height: 25%;" },
    { value: "h-2/4", desc: "height: 50%;" },
    { value: "h-3/4", desc: "height: 75%;" },
    { value: "h-1/5", desc: "height: 20%;" },
    { value: "h-2/5", desc: "height: 40%;" },
    { value: "h-3/5", desc: "height: 60%;" },
    { value: "h-4/5", desc: "height: 80%;" },
    { value: "h-1/6", desc: "height: 16.666667%;" },
    { value: "h-2/6", desc: "height: 33.333333%;" },
    { value: "h-3/6", desc: "height: 50%;" },
    { value: "h-4/6", desc: "height: 66.666667%;" },
    { value: "h-5/6", desc: "height: 83.333333%;" },
    { value: "h-full", desc: "height: 100%;" },
    { value: "h-screen", desc: "height: 100vh;" },
    { value: "h-svh", desc: "height: 100svh;" },
    { value: "h-lvh", desc: "height: 100lvh;" },
    { value: "h-dvh", desc: "height: 100dvh;" },
    { value: "h-min", desc: "height: min-content;" },
    { value: "h-max", desc: "height: max-content;" },
    { value: "h-fit", desc: "height: fit-content;" },
  ],
  "min-height": [
    { value: "min-h-0", desc: "min-height: 0px;" },
    { value: "min-h-1", desc: "min-height: 0.25rem; /* 4px */" },
    { value: "min-h-2", desc: "min-height: 0.5rem; /* 8px */" },
    { value: "min-h-3", desc: "min-height: 0.75rem; /* 12px */" },
    { value: "min-h-4", desc: "min-height: 1rem; /* 16px */" },
    { value: "min-h-5", desc: "min-height: 1.25rem; /* 20px */" },
    { value: "min-h-6", desc: "min-height: 1.5rem; /* 24px */" },
    { value: "min-h-7", desc: "min-height: 1.75rem; /* 28px */" },
    { value: "min-h-8", desc: "min-height: 2rem; /* 32px */" },
    { value: "min-h-9", desc: "min-height: 2.25rem; /* 36px */" },
    { value: "min-h-10", desc: "min-height: 2.5rem; /* 40px */" },
    { value: "min-h-11", desc: "min-height: 2.75rem; /* 44px */" },
    { value: "min-h-12", desc: "min-height: 3rem; /* 48px */" },
    { value: "min-h-14", desc: "min-height: 3.5rem; /* 56px */" },
    { value: "min-h-16", desc: "min-height: 4rem; /* 64px */" },
    { value: "min-h-20", desc: "min-height: 5rem; /* 80px */" },
    { value: "min-h-24", desc: "min-height: 6rem; /* 96px */" },
    { value: "min-h-28", desc: "min-height: 7rem; /* 112px */" },
    { value: "min-h-32", desc: "min-height: 8rem; /* 128px */" },
    { value: "min-h-36", desc: "min-height: 9rem; /* 144px */" },
    { value: "min-h-40", desc: "min-height: 10rem; /* 160px */" },
    { value: "min-h-44", desc: "min-height: 11rem; /* 176px */" },
    { value: "min-h-48", desc: "min-height: 12rem; /* 192px */" },
    { value: "min-h-52", desc: "min-height: 13rem; /* 208px */" },
    { value: "min-h-56", desc: "min-height: 14rem; /* 224px */" },
    { value: "min-h-60", desc: "min-height: 15rem; /* 240px */" },
    { value: "min-h-64", desc: "min-height: 16rem; /* 256px */" },
    { value: "min-h-72", desc: "min-height: 18rem; /* 288px */" },
    { value: "min-h-80", desc: "min-height: 20rem; /* 320px */" },
    { value: "min-h-96", desc: "min-height: 24rem; /* 384px */" },
    { value: "min-h-px", desc: "min-height: 1px;" },
    { value: "min-h-0.5", desc: "min-height: 0.125rem; /* 2px */" },
    { value: "min-h-1.5", desc: "min-height: 0.375rem; /* 6px */" },
    { value: "min-h-2.5", desc: "min-height: 0.625rem; /* 10px */" },
    { value: "min-h-3.5", desc: "min-height: 0.875rem; /* 14px */" },
    { value: "min-h-full", desc: "min-height: 100%;" },
    { value: "min-h-screen", desc: "min-height: 100vh;" },
    { value: "min-h-svh", desc: "min-height: 100svh;" },
    { value: "min-h-lvh", desc: "min-height: 100lvh;" },
    { value: "min-h-dvh", desc: "min-height: 100dvh;" },
    { value: "min-h-min", desc: "min-height: min-content;" },
    { value: "min-h-max", desc: "min-height: max-content;" },
    { value: "min-h-fit", desc: "min-height: fit-content;" },
  ],
  "max-height": [
    { value: "max-h-0", desc: "max-height: 0px;" },
    { value: "max-h-px", desc: "max-height: 1px;" },
    { value: "max-h-0.5", desc: "max-height: 0.125rem; /* 2px */" },
    { value: "max-h-1", desc: "max-height: 0.25rem; /* 4px */" },
    { value: "max-h-1.5", desc: "max-height: 0.375rem; /* 6px */" },
    { value: "max-h-2", desc: "max-height: 0.5rem; /* 8px */" },
    { value: "max-h-2.5", desc: "max-height: 0.625rem; /* 10px */" },
    { value: "max-h-3", desc: "max-height: 0.75rem; /* 12px */" },
    { value: "max-h-3.5", desc: "max-height: 0.875rem; /* 14px */" },
    { value: "max-h-4", desc: "max-height: 1rem; /* 16px */" },
    { value: "max-h-5", desc: "max-height: 1.25rem; /* 20px */" },
    { value: "max-h-6", desc: "max-height: 1.5rem; /* 24px */" },
    { value: "max-h-7", desc: "max-height: 1.75rem; /* 28px */" },
    { value: "max-h-8", desc: "max-height: 2rem; /* 32px */" },
    { value: "max-h-9", desc: "max-height: 2.25rem; /* 36px */" },
    { value: "max-h-10", desc: "max-height: 2.5rem; /* 40px */" },
    { value: "max-h-11", desc: "max-height: 2.75rem; /* 44px */" },
    { value: "max-h-12", desc: "max-height: 3rem; /* 48px */" },
    { value: "max-h-14", desc: "max-height: 3.5rem; /* 56px */" },
    { value: "max-h-16", desc: "max-height: 4rem; /* 64px */" },
    { value: "max-h-20", desc: "max-height: 5rem; /* 80px */" },
    { value: "max-h-24", desc: "max-height: 6rem; /* 96px */" },
    { value: "max-h-28", desc: "max-height: 7rem; /* 112px */" },
    { value: "max-h-32", desc: "max-height: 8rem; /* 128px */" },
    { value: "max-h-36", desc: "max-height: 9rem; /* 144px */" },
    { value: "max-h-40", desc: "max-height: 10rem; /* 160px */" },
    { value: "max-h-44", desc: "max-height: 11rem; /* 176px */" },
    { value: "max-h-48", desc: "max-height: 12rem; /* 192px */" },
    { value: "max-h-52", desc: "max-height: 13rem; /* 208px */" },
    { value: "max-h-56", desc: "max-height: 14rem; /* 224px */" },
    { value: "max-h-60", desc: "max-height: 15rem; /* 240px */" },
    { value: "max-h-64", desc: "max-height: 16rem; /* 256px */" },
    { value: "max-h-72", desc: "max-height: 18rem; /* 288px */" },
    { value: "max-h-80", desc: "max-height: 20rem; /* 320px */" },
    { value: "max-h-96", desc: "max-height: 24rem; /* 384px */" },
    { value: "max-h-none", desc: "max-height: none;" },
    { value: "max-h-full", desc: "max-height: 100%;" },
    { value: "max-h-screen", desc: "max-height: 100vh;" },
    { value: "max-h-svh", desc: "max-height: 100svh;" },
    { value: "max-h-lvh", desc: "max-height: 100lvh;" },
    { value: "max-h-dvh", desc: "max-height: 100dvh;" },
    { value: "max-h-min", desc: "max-height: min-content;" },
    { value: "max-h-max", desc: "max-height: max-content;" },
    { value: "max-h-fit", desc: "max-height: fit-content;" },
  ],
  hyphens: [
    { value: "hyphens-none", desc: "hyphens: none;" },
    { value: "hyphens-manual", desc: "hyphens: manual;" },
    { value: "hyphens-auto", desc: "hyphens: auto;" },
  ],
  "white-space": [
    { value: "whitespace-normal", desc: "white-space: normal;" },
    { value: "whitespace-nowrap", desc: "white-space: nowrap;" },
    { value: "whitespace-pre", desc: "white-space: pre;" },
    { value: "whitespace-pre-line", desc: "white-space: pre-line;" },
    { value: "whitespace-pre-wrap", desc: "white-space: pre-wrap;" },
    { value: "whitespace-break-spaces", desc: "white-space: break-spaces;" },
  ],
  "pointer-events": [
    { value: "pointer-events-none", desc: "pointer-events: none;" },
    { value: "pointer-events-auto", desc: "pointer-events: auto;" },
  ],
  "user-select": [
    { value: "select-none", desc: "user-select: none;" },
    { value: "select-text", desc: "user-select: text;" },
    { value: "select-all", desc: "user-select: all;" },
    { value: "select-auto", desc: "user-select: auto;" },
  ],
};
module.exports = styles;
